"""
User model (reference from Spec 1 - Authentication & User Management).

This model represents the users table created and managed by the frontend
authentication system (Better Auth). The backend DOES NOT create or modify
this table - it only references it via foreign key in the Task model.
"""

from sqlmodel import SQLModel, Field
from datetime import datetime
from typing import Optional


class User(SQLModel, table=True):
    """
    User model from Spec 1 (Better Auth).

    Backend DOES NOT create or modify this table.
    Only referenced via foreign key in Task model.

    The users table is created by the frontend authentication system
    and contains user credentials and profile information.
    """

    __tablename__ = "users"

    # Primary Key - UUID generated by Better Auth
    id: str = Field(
        primary_key=True,
        description="UUID generated by Better Auth on user signup"
    )

    # User Credentials
    email: str = Field(
        unique=True,
        index=True,
        max_length=255,
        description="User's email address, unique across system"
    )

    password_hash: str = Field(
        max_length=255,
        description="bcrypt-hashed password (managed by Better Auth)"
    )

    # Timestamps
    created_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="User registration timestamp"
    )

    updated_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="Last profile update timestamp"
    )

    class Config:
        """SQLModel configuration."""
        # This model is read-only from backend perspective
        # Backend should never insert/update/delete users
        # Note: validate_assignment removed due to Pydantic v2 compatibility issues with SQLModel
        pass
